dist: trusty
language: python
python:
  - "3.5"
  - "3.6"
env:
  - TEST_DB=SQLite
  - TEST_DB=MySQL
  - TEST_DB=Postgres
services:
  - mysql
  - postgresql
  - sshd
before_install:
  - mysql -e 'SELECT VERSION();'
  - mysql -e 'CREATE USER "tester" IDENTIFIED BY "";'
  - mysql -e 'CREATE DATABASE collection_db CHARACTER SET utf8 COLLATE utf8_unicode_ci;'
  - mysql -e 'GRANT ALL PRIVILEGES ON collection_db.* TO tester;'

  - psql -c  "CREATE DATABASE collection_db ENCODING 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8';" -U postgres
install:
  - pip install -r requirements/devel.txt
  - pip install coveralls
script:
  - ./run_tests.sh && mv .coverage .coverage.unit_test
  # run integration tests
  - cd src/ && python ./server.py ../.config.travis && cp .coverage ../.coverage.integration_test && cd ../
  - coverage combine .coverage.*
after_success:
  - coveralls
notifications:
  email:
    on_failure: change
    on_success: change
