dist: trusty
language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements/devel.txt
  - pip install coveralls
script:
  - ./run_tests.sh
after_success:
  - coveralls
notifications:
  email:
    on_failure: change
    on_success: change
